---

- name: Set internal variable platform-suffix
  set_fact:
    _platform_suffix: 'linux_amd64'
  when: ansible_userspace_bits == '64'

- name: Set internal variable platform-suffix
  set_fact:
    _platform_suffix: 'linux_386'
  when: ansible_userspace_bits == '32'

- name: Download client binary
  get_url:
    url: '{{ restic_url }}'
    dest: '/tmp/'
  register: get_url_restic

- name: Decompress the binary
  shell: "bzip2 -dc {{ get_url_restic.dest }} > {{ restic_install_path }}/restic"
  args:
    creates: '{{ restic_install_path }}/restic'

- name: Ensure permissions are correct
  file:
    path: '{{ restic_install_path }}/restic'
    mode: '0755'
    owner: 'root'
    group: 'root'
