---

- hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Ensure python2 is present
      raw: 'which python || apt-get install -y python python-simplejson'
      changed_when: false

- hosts: all
  become: true
  vars:
    restic_redirection: '> /var/log/restic/out.log 2> /var/log/restic/err.log'

    restic_repos:
      - name: test
        url: '/backup'
        password: 'testpassword'

    restic_jobs:
      - at: '0 6  * * *'
        type: 'db_mysql'
        arg: 'blog'
        hostname: 'foo.bar'
        redirection: '2> /var/log/restic/err.log'
      - at: '0 8  * * *'
        type: 'db_pgsql'
        arg: 'users'
        hostname: 'bar.foo'
        tags:
          - postgres
          - database

    restic_jobs_raw:
      - command: 'restic backup /var'
        at: '0 4  * * *'
      - command: 'restic backup /home'
        at: '0 3  * * *'
        user: 'backup'

  roles:
    - ansible-restic

  tasks:
    - name: run `restic version`
      command: restic version
      register: cmd_restic_version
      changed_when: false

    - name: ensure versions match
      assert:
        that:
          - "restic_version in cmd_restic_version.stdout"
        msg: 'restic version does not match to that in restic_version'

    - name: install python pip
      apt:
        name: 'python-pip'

    - name: install chkcrontab
      pip:
        name: 'chkcrontab'

    - name: verifying crontab file with chkcrontab
      shell: 'chkcrontab /etc/cron.d/restic-*'
      register: cmd_chkcrontab
      changed_when: false
